version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - service-networks
    volumes:
      - "data:/data/db"
    expose:
      - ${PG_PORT}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADM_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADM_PASSWORD}
    ports:
      - ${ADM_PORT}:80
    expose:
      - ${ADM_PORT}
    depends_on:
      - postgres
    networks:
      - service-networks

  quarkus:
    container_name: quarkus-app
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    restart: always
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PG_PORT=${PG_PORT}
      - JWT_ISSUER=${JWT_ISSUER}
      - APP_API_KEY=${APP_API_KEY}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - QUARKUS_DATASOURCE_REACTIVE_URL=${QUARKUS_DATASOURCE_REACTIVE_URL}
      - QUARKUS_DATASOURCE_USERNAME=${PG_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${PG_PASSWORD}
      - QUARKUS_HTTP_CORS_ENABLED=${QUARKUS_HTTP_CORS_ENABLED}
      - QUARKUS_HTTP_CORS_ORIGINS=${QUARKUS_HTTP_CORS_ORIGINS}
      - QUARKUS_HTTP_CORS_METHODS=${QUARKUS_HTTP_CORS_METHODS}
      - QUARKUS_HTTP_CORS_HEADERS=${QUARKUS_HTTP_CORS_HEADERS}
      - QUARKUS_HTTP_CORS_ACCESS_CONTROL_ALLOW_CREDENTIALS=${QUARKUS_HTTP_CORS_ACCESS_CONTROL_ALLOW_CREDENTIALS}
      - QUARKUS_TLS_TRUST_ALL=${QUARKUS_TLS_TRUST_ALL}
      - QUARKUS_PROFILE=DEV
    ports:
      - ${QUARKUS_PORT}:8080
    depends_on:
      - postgres
    expose:
      - ${QUARKUS_PORT}
    networks:
      - service-networks

networks:
  service-networks:
    driver: bridge

volumes:
  data:
    driver: "local"
